### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Schwuuuuup** [Apen/additional_reports#1]
Hi,

the dependencies of additional_reports 3.0.3 are still bad because TYPO3 is written uppercase, it and PHP has to be lowercase there... :-/

Regards
TOM

**Comment by Apen** [comment]
Hi,

I am aware of it, i use https://github.com/etobi/Typo3ExtensionUtils to upload my extension and it seems to add an uppercase...

I will check that

**Comment by Apen** [comment]
I think everything its ok now.
