### ISSUE TITLE
Add t3lib_div::getIndpEnv information

### ISSUE THREAD

**Issue by gaumondp** [Apen/additional_reports#12]
In TYPO3 4.5 and before, going into the Install Tool:phpinfo() we used to get a "DEBUG information" section and a t3lib_div::getIndpEnv section now missing in 6.2.

Maybe add this back into additional_reports ?

![image](https://cloud.githubusercontent.com/assets/5972510/5845501/7682a2b6-a18a-11e4-989c-d288fc698613.png)

**Comment by Apen** [comment]
Ok, see commit : https://github.com/Apen/additional_reports/commit/ea3ea64859146eb95a48400f41d11c38517d7790

**Comment by gaumondp** [comment]
Works perfect on my TYPO3 6.2.9. Thanks for the feature !
