### ISSUE TITLE
composer installation with version constraint "dev-master" not possible

### ISSUE THREAD

**Issue by josefglatz** [Apen/additional_reports#12]
Hi,

I actually want to use/test the extension in a composer based 8.7 TYPO3 instance.

For some reason, it's not possible to use the master branch with `composer require apen/additional_reports:dev-master`. The reason why I want to use master is, because actually composer based installation is only possible you release a new version.

Anyway, a version constraint on the git branch at github should be possible to use anyway.

I couldn't found the reason, why `dev-master` is not found by packagist. Did you included the packagist hook in your github repo @Apen?

**Comment by Apen** [comment]
yes the webhook was here, but there was a problem with the repo update.
Check the last branch, it works with packagist
