### ISSUE TITLE
composer install - not in typo3conf/ext

### ISSUE THREAD

**Issue by lukasniestroj** [Apen/additional_reports#13]
I just tried to install the extension via composer ... the whole package was installed in the vendor folder !

Please add "type": "typo3-cms-extension" into composer.json.

**Comment by Patta** [comment]
I can confirm this with `3.1.2` of `apen/additional_reports`

**Comment by Apen** [comment]
I dont get it because its the case since a long time.
Packagist have an error that i have fix, maybe it work better now

**Comment by Apen** [comment]
ok ok, i never pushed the modif to a new version. Try the 3.1.3
Sorry for this

**Comment by Patta** [comment]
@Apen with 3.1.3 it works

**Comment by Apen** [comment]
ok, im glad to hear that 👍
