### ISSUE TITLE
I cannot reach every Report option

### ISSUE THREAD

**Issue by webfacer** [Apen/additional_reports#15]
System: 
Typo3 = 8.7.19
PHP = 7.2.x
Nginx

For some reason i am getting following error:

on following Report options:
- general status `PHP Warning: Use of undefined constant TYPO3_db - assumed 'TYPO3_db' (this will throw an Error in a future version of PHP) in /var/www/html/typo3conf/ext/additional_reports/Classes/Main.php line 390`
- on this two i am getting same issue _**check the database**_ &  and **_load extension list_**  `PHP Warning: Use of undefined constant TYPO3_db - assumed 'TYPO3_db' (this will throw an Error in a future version of PHP) in /var/www/html/typo3conf/ext/additional_reports/Classes/Utility.php line 727`

I just installed it and cleared all caches also remove everything from my typo3temp, then the options appeared. then i wanted to check every option and what i got was this Errors on 3 different options.
Am i missing something?

**Comment by Apen** [comment]
You dont miss something, i think i have to fix the "old" database access.
Stay tuned :-)

**Comment by Apen** [comment]
Just try the last commit, it will works @webfacer

**Comment by webfacer** [comment]
thx i will try

**Comment by webfacer** [comment]
hmm should it work already with composer? because i do not get the package updated when updating composer.

**Comment by Apen** [comment]
Strange... Test now, you will get the 3.1.4 on packagist

**Comment by webfacer** [comment]
yeah thanks it works now.
