### ISSUE TITLE
Replace Call to undefined method ExtensionManagementUtility::extRelPath() fpr Typo3 9.x compatibility

### ISSUE THREAD

**Issue by schrej-zz** [Apen/additional_reports#17]
Call to undefined method TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath()
Call in /Classes/Main.php line 33 should be replaced by either

use PathUtility::getAbsoluteWebPath()
or
->siteRelPath()

**Comment by Apen** [comment]
Fix in last version
