### ISSUE TITLE
Version 3.2.1 breaks compare functions

### ISSUE THREAD

**Issue by tobiasschaeferptb** [Apen/additional_reports#21]
Hello, 

since the 3.2.1 update of additional_reports the compare function for extensions doesn't work anymore. The reason is a incorrect inclusion of 3 files.
In the error log you will find errors like this once you click on the "Compare with same version" button: 
Core: Error handler (BE): PHP Warning: file_get_contents(/srv/www/vhosts/website/typo3//srv/www/vhosts/website/typo3conf/ext/additional_reports/Resources/Public/Shadowbox/shadowbox.css): failed to open stream: No such file or directory in /srv/www/libs/typo3_src-8.7.29/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 359 
Core: Error handler (BE): PHP Warning: file_get_contents(/srv/www/vhosts/website/typo3//srv/www/vhosts/website/typo3conf/ext/additional_reports/Resources/Public/Css/tx_additionalreports.css): failed to open stream: No such file or directory in /srv/www/libs/typo3_src-8.7.29/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 359 
Core: Error handler (BE): PHP Warning: file_get_contents(/srv/www/vhosts/website/typo3//srv/www/vhosts/website/typo3conf/ext/additional_reports/Resources/Public/Shadowbox/shadowbox.js): failed to open stream: No such file or directory in /srv/www/libs/typo3_src-8.7.29/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 287

The TYPO3 version is 8.7.29. With version 3.1.4 the compare function worked.

Best regards,
Tobias

**Comment by Apen** [comment]
Fix in 3.2.2
