### ISSUE TITLE
Report for extensions fails if no self developed or unloaded extensions are present

### ISSUE THREAD

**Issue by tobiasschaeferptb** [Apen/additional_reports#22]
Hello,

In TYPO3 9.5.15, additional_reports 3.2.2 and PHP 7.2.23 the report for extensions fails if there aren't any self developed or unloaded extensions present in the system. The error message is:
PHP Warning: count(): Parameter must be an array or an object that implements Countable in typo3conf/ext/additional_reports/Classes/Reports/Extensions.php line 59
There are 3 lines with count($allExtension['dev']) (59, 72 and 76) and 1 line with count($allExtension['unloaded']) (65).
I would recommend to define variables like $count_dev and $count_unloaded instead of using count($allExtension['dev']) and count($allExtension['unloaded']) without checking if $allExtension['dev'] and $allExtension['unloaded'] is something that can be counted:
$count_dev = is_array($allExtension['dev']) && count($allExtension['dev']) ? count($allExtension['dev']) : 0;
$count_unloaded = is_array($allExtension['unloaded']) && count($allExtension['unloaded']) ? count($allExtension['unloaded']) : 0;

Cheers, Tobias

**Comment by Apen** [comment]
Fix in this last commit
