### ISSUE TITLE
Iam using typo3 10.x , and i have installed tt_product extn, getting TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\ExtensionManagementUtility::siteRelPath() 

### ISSUE THREAD

**Issue by jogowda** [Apen/additional_reports#25]
TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Utility\ExtensionManagementUtility::siteRelPath() | Error thrown in file /var/www/project_name/web/typo3conf/ext/tt_products/ext_localconf.php in line 43

siteRelPath() should be replace with some other function ? Please suggest me what is the problem here?

**Comment by Apen** [comment]
It is not related to additional_reports, you use a tt_product version not compatible with TYPO3 10.
