### ISSUE TITLE
Error in PlugIn Overview

### ISSUE THREAD

**Issue by Finulin** [Apen/additional_reports#29]
![image](https://user-images.githubusercontent.com/31020053/152523990-f05ca912-0ca4-4687-ab2f-e3c7509f8622.png)

i use TYPO3 11.5.4

**Comment by schrej-zz** [comment]
Hi,
can confirm this issue.

**Comment by Apen** [comment]
Hi guys, seems to happen when extension/ctype is not loaded/find. You can test with my last commit.

**Comment by schrej-zz** [comment]
Hi @Apen,
can now confirm, that your patch is working.
Thanks Joerg
