### ISSUE TITLE
Extension breaks TYPO3 installations running with PHP 5.3

### ISSUE THREAD

**Issue by andre-spindler** [Apen/additional_reports#3]
In ext_localconf.php you use the new short array syntax, introduced with PHP 5.4.
Minimum requirement for TYPO3 6.2 is PHP 5.3, but doing so, the installation of current version 3.0.7 breaks. Both frontend and backend fail.

This should be fixed by just add the php version to the constraints in ext_emconf.php.
I have not checked in what version this was introduced.

Thanks,
André Spindler

**Comment by Apen** [comment]
Its clearly not a "need" syntax here, so i use old style to be backward compatible.
Check last commit

**Comment by andre-spindler** [comment]
New version 3.0.8 works.
Thanks!
