### ISSUE TITLE
Newest TYPO3 Version throws errors and functions not working

### ISSUE THREAD

**Issue by aleksej-gustke** [Apen/additional_reports#30]
TYPO3 Version: 11.5.13
Extension Version: 3.4.1
PHP Version: 7.4

In the Additional reports - loaded extension list view none of the buttons seem to work.
No console error, no network error.

In Additional reports - plugins & content type a 503 Error gets thrown:
Argument 1 passed to TYPO3\CMS\Core\Utility\PathUtility::isExtensionPath() must be of the type string, null given, called in /srv/www/libs/typo3_src-11.5.13/typo3/sysext/core/Classes/Localization/LanguageStore.php on line 164

**Comment by Apen** [comment]
All is fixed in TER 3.4.2, thanks for your report
