### ISSUE TITLE
Undefined array key "extConf" in xxx/additional_reports/Classes/Reports/Plugins.php line 43

### ISSUE THREAD

**Issue by WSBusch** [Apen/additional_reports#35]
When calling the report "Additional reports - plugins and content type" the error message appears 

`PHP Warning: Undefined array key "extConf" in /xxx/typo3conf/ext/additional_reports/Classes/Reports/Plugins.php line 43`
`$view->assign('extconf', unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['additional_reports']));`

TYPO3 11.5.25
PHP 8.1
Extension 3.4.3

Is it possible that the extension is not yet PHP8 ready?

**Comment by Apen** [comment]
Yes, i need to work on this PHP 8.1 compat. 
Sorry, its on my todolist...

**Comment by Apen** [comment]
You can try with the last GIT version, i push some fixes.

**Comment by WSBusch** [comment]
In our case, everything is now working as it should.
Thanks a lot
