### ISSUE TITLE
Display of plugins in summary view of plugins and content types report is broken

### ISSUE THREAD

**Issue by tbsschmdt** [Apen/additional_reports#39]
* Icons of plugins are not displayed because of a wrong path
* Plugin title is missing

**Comment by Apen** [comment]
Hi, and thanks for your PR, wich typo3 version do you use?

**Comment by tbsschmdt** [comment]
It's TYPO3 11.

**Comment by Apen** [comment]
Did you use composer?

**Comment by tbsschmdt** [comment]
Yes, it's a composer setup. And I used version 3.4.5 of this extension. (I just see you already merged my pull request. Thanks!)

**Comment by Apen** [comment]
Thanks, good to me :-)

**Comment by Apen** [comment]
i made a small commit to refactor the logic behind the icons/labels of extensions in Plugins. Could you check if everything is always OK in the last git update?

**Comment by tbsschmdt** [comment]
I tested the changes from your commit d283b8ba6930cb1c8b19a3d373bf3f4fcb0de8fe in TYPO3 11 and can confirm that they work as expected. Thanks!

**Comment by Apen** [comment]
👍
