### ISSUE TITLE
Pagination is broken in TYPO3 11

### ISSUE THREAD

**Issue by tbsschmdt** [Apen/additional_reports#41]
Commit 2aeadbef237fde726544813258840ed161e22666 breaks pagination in TYPO3 11. Pagination links redirect to reports overview. Parameter *report* has a different value now:

working pagination link:
*typo3/module/system/reports?token=TOKEN&currentPage=2&action=detail&extension=additional_reports&report=plugins* 

broken pagination link:
*typo3/module/system/reports?token=TOKEN&currentPage=2&action=detail&extension=additional_reports&report=additionalreports_plugins*

**Comment by Apen** [comment]
Should be fixed in last commit

**Comment by tbsschmdt** [comment]
Could you please release a new version that includes 79ed656e01722bf7ad0ea6e7b9e7100f75fe28bb

**Comment by Apen** [comment]
Publishing now
