### ISSUE TITLE
[BUG] Content Security Policy in 'plugins  content type'

### ISSUE THREAD

**Issue by ste101** [Apen/additional_reports#43]
I'm getting this error when selecting 'plugins  content type' with activated 'Security: backend enforce content security policy':
`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-WI_zioRv4UnzdcueKlie2mZ6tmx46LqnwQ9ANaICSW9kTCpce9iBaQ' 'report-sample'". Either the 'unsafe-inline' keyword, a hash ('sha256-hR9evmmtfYpk8OMZk2os+R4KO344Hmnek+AWnmYlWFc='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by Apen** [comment]
Must be fixed in the last commit
