### ISSUE TITLE
ViewHelper f:security.nonce breaks plugin and content type report in TYPO3 11

### ISSUE THREAD

**Issue by tbsschmdt** [Apen/additional_reports#49]
Current version 3.4.7 uses the ViewHelper f:security.nonce that is only available in TYPO3 12 but not yet in TYPO3 11. Therefore the plugin and content type report throws an error message in TYPO3 11. I guess version 3.4.7 is just not compatible with TYPO3 11. Please update the version constraints.

**Comment by tbsschmdt** [comment]
The breaking change has been introduced with 396ad29 to fix #43

**Comment by Apen** [comment]
I externalize the JS for this. Must work with 11/12 on the last commit
