### ISSUE TITLE
Not compatible with TYPO3 v8 LTS (8.7)

### ISSUE THREAD

**Issue by Patta** [Apen/additional_reports#5]
composer why-not typo3/cms:8.7.0

typo3-ter/additional-reports                   3.0.9    requires          typo3/cms-core (>= 6.2.0, <= 7.6.99)

**Comment by Apen** [comment]
I have a lot of works to do to be compatible with 8 LTS.
Some javascript to convert, queries, templates, etc...

It's on my todo list.

**Comment by rorentz** [comment]
Would be really nice, if you get it to work!

**Comment by Apen** [comment]
You can test the last commit. It works on the last LTS.
I still have a some clean to do and bug to fix.

Let me know if you find some bugs.
